### ISSUE TITLE
이게 머시여

### ISSUE THREAD

**Issue by neuwcodebox** [phillyai/ChristmasTree#1]
솔로 약올리는 거시여?
농담이고.. 이거 어떻게 실행하죠.

**Comment by 20chan** [comment]
소스 한줄도 안짰다는게 함정

**Comment by neuwcodebox** [comment]
@phillyai 에엥.... 24일까진 완성하시죳!

**Comment by 20chan** [comment]
@NeuroWhAI 그래야 겠쪄 ㅇㅅㅇ 근데 시험기간이고 레포데가 너무 재밌어서

**Comment by neuwcodebox** [comment]
@phillyai 잠깐ㅋㅋㅋㅋㅋㅋ 둘이 양립하면 안되죸ㅋㅋㅋㅋ

**Comment by 20chan** [comment]
오늘도 세개의 스토리를 깼어요 (뿌듯
또 오늘도 네개의 과목을 시험봤고 7개가 남았쬬
